version: "3.8"

services:

  fiap--integrations-api:
    container_name: fiap--integrations-api
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: fiap--integrations-api/
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: local
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"